#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -pe omp 16

source /etc/bashrc

module load subread

GTF=/projectnb/bf528/project_3/reference/rn4_refGene_20180308.gtf

#Using for loop to output featureCounts for sample files
for FILE in /projectnb/bf528/users/tinman/Project3/datacurator/star_results2/*.bam
    do
        samples=$(basename "$FILE")
        OUT=/projectnb/bf528/users/tinman/Project3/programmer/featureCounts/$samples.txt
        featureCounts -T 16 -a $GTF -o $OUT $FILE
    done

